apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ .Values.nameOverride }}
    chart: {{ .Values.nameOverride }}
  name: {{ .Values.nameOverride }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ .Values.nameOverride }}
    namespace: {{ .Values.namespace }}